apiVersion: v1
kind: Secret
metadata:
  name: db-backup-secret
type: Opaque
stringData:
  DB_BACKUP_PREFIX: "DB_BACKUP_PREFIX"
  DATABASE_URL: "postgresql://username:domain:port/database"
  AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
  S3_ENDPOINT_URL: "S3_ENDPOINT_URL"
  S3_BUCKET: "S3_BUCKET"