apiVersion: v1
kind: Secret
metadata:
  name: db-backup-secret
type: Opaque
stringData:
  DB_BACKUP_PREFIX: "ton-dev"
  DATABASE_URL: "postgresql://username:domain:port/database"
  AWS_ACCESS_KEY_ID: "YOUR_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "YOUR_SECRET_ACCESS_KEY"
  S3_ENDPOINT_URL: "https://rsquad-backup.fra1.digitaloceanspaces.com"
  S3_BUCKET: "rsquad-backup"