{{- if and .Values.ingress .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- if index .Values.ingress "letsencrypt-issuer" }}
    cert-manager.io/cluster-issuer: {{ index .Values.ingress "letsencrypt-issuer" | quote }}
    {{- end }}
spec:
  ingressClassName: "nginx"
  {{- if index .Values.ingress "letsencrypt-issuer" }}
  tls:
    - hosts:
        {{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ (index .Values.ingress.hosts 0).host | quote }}-tls
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" $ }}
                {{- if and .Values.service .Values.service "port" }}
                port:
                  number: {{ .Values.service.port }}
                {{- else }}
                port:
                  number: 80 # Default to 80 if not specified
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}