{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
type: Opaque
data:
  my-secret: {{ index .Values.secret "my-secret" | b64enc }}
{{- end }}
