{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    app: {{ include "app.name" . }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }} # Default to ClusterIP if not specified
  ports:
    - port: {{ .Values.service.port | default 80 }} # Default to 80 if not specified
      targetPort: {{ .Values.service.targetPort | default 3000 }} # Default to 3000 if not specified
  selector:
    app: {{ include "app.name" . }}
{{- end }}