{{- if and $.Values.deploymentType (eq .Values.deploymentType "StatefulSet") }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.name" $ }}
  labels:
    app: {{ include "app.name" $ }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
      maxUnavailable: "50%"
  replicas: {{ $.Values.replicaCount }}
  podManagementPolicy: Parallel
  serviceName: {{ include "app.name" $ }}-headless
  selector:
    matchLabels:
      app: {{ include "app.name" $ }}
  template:
    metadata:
      labels:
        app: {{ include "app.name" $ }}
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: oracle
          image: {{ $.Values.image.repository }}:{{ $.Values.image.tag | default "latest" }}
          imagePullPolicy: {{ $.Values.image.pullPolicy | default "IfNotPresent" }}
          {{- if $.Values.CustomInitScript }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              {{ $.Values.CustomInitScript | nindent 14 }}
          {{- end }}
          {{- if or $.Values.configMapName $.Values.secretName }}
          envFrom:
            {{- if $.Values.configMapName }}
            - configMapRef:
                name: {{ $.Values.configMapName }}
            {{- end }}
            {{- if $.Values.secretName }}
            - secretRef:
                name: {{ $.Values.secretName }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ $.Values.storage.path }}
      imagePullSecrets:
        - name: docker-registry-creds
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ $.Values.storage.size }}
{{- end }}