{{- if and .Values.deploymentType (eq .Values.deploymentType "StatefulSet") }}
{{- range $i, $_ := until (.Values.replicaCount | int) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.name" . }}-{{ $i }}
  labels:
    app: {{ include "app.name" . }}
    instance: "{{ $i }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "app.name" . }}
      instance: "{{ $i }}"
  template:
    metadata:
      labels:
        app: {{ include "app.name" . }}
        instance: "{{ $i }}"
    spec:
      containers:
        - name: oracle
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          {{- if or .Values.configMapName .Values.secretName }}
          env:
            {{- if .Values.configMapName }}
            - configMapRef:
                name: {{ .Values.configMapName }}
            {{- end }}
            {{- if .Values.secretName }}
            {{- range $key, $name := .Values.SecretNames }}
            - name: {{ $name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: {{ $name }}-{{ $i }}
            {{- end }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /home/apps/oracle/data
      imagePullSecrets:
        - name: docker-registry-creds
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ $.Values.storage.class }}
        resources:
          requests:
            storage: {{ $.Values.storage.size }}
{{- end }}
{{- end }}