command:
  - "/bin/sh"
  - "-c"
  - |
    sed "s|\$TELEGRAM_BOT_TOKEN|${TELEGRAM_BOT_TOKEN}|g" /etc/alertmanager/alertmanager.yml > /alertmanager/alertmanager.yml \
    && exec /bin/alertmanager --config.file=/alertmanager/alertmanager.yml
config:
  enabled: true
  global: {}
  route:
    group_interval: 2m
    group_wait: 2m
    receiver: telegram_receiver
    repeat_interval: 3h
    routes:
    - match:
        severity: critical
      group_by: ["name"]
      receiver: telegram_receiver
      repeat_interval: 1h
    - match:
        severity: warning
      group_by: ["name"]
      receiver: telegram_receiver
      repeat_interval: 3h
  templates:
  - /etc/alertmanager/*.tmpl
extraEnv:
  - name: TELEGRAM_BOT_TOKEN
    valueFrom:
      secretKeyRef:
        key: bot_token
        name: telegram-bot-token
templates:
  telegram.tmpl: >-
    {{ define "telegram.text" }}
    {{ $first := index .Alerts 0 }}
    {{ $severity := $first.Labels.severity }}
    {{ if eq .Status "firing" -}}
    {{ if eq $severity "warning" -}}
    ⚠️ <b>FIRING</b>
    {{ else if eq $severity "critical" -}}
    🔴 <b>FIRING</b>
    {{ else -}}
    ℹ️ <b>FIRING</b>
    {{ end -}}
    {{ else if eq .Status "resolved" -}}
    ✅ <b>RESOLVED</b>
    {{ end -}}
    <b>{{ .CommonLabels.alertname }}</b>
    {{ range .Alerts -}}
    {{ if .Labels.name -}}
    <b>🎯Affected: </b>{{ .Labels.name }}
    {{ end -}}
    {{ if eq $.Status "firing" -}}
    <b>⏰Date/Time: </b>{{ .StartsAt.Format "Mon 02 Jan 15:04:05 MST 2006" }}
    {{ else if eq $.Status "resolved" -}}
    <b>⏰Date/Time: </b>{{ .EndsAt.Format "Mon 02 Jan 15:04:05 MST 2006" }}
    {{ end -}}
    <b>Description: </b>{{ .Annotations.description }}
    {{ if or .Labels.balance .Labels.addr .Labels.instance .Labels.threshold -}}
    <b>Details: </b>
    {{ if .Annotations.balance -}}
    - <b>Balance: </b>{{ .Annotations.balance }}
    {{ end -}}
    {{ if .Annotations.threshold -}}
    - <b>Threshold: </b>{{ .Annotations.threshold }}
    {{ end -}}
    {{ if .Labels.instance -}}
    - <b>Source: </b>{{ reReplaceAll ":.*" "" .Labels.instance }}
    {{ end -}}
    {{ if .Annotations.namespace -}}
    - <b>Namespace: </b>{{ reReplaceAll ":.*" "" .Annotations.namespace }}
    {{ end -}}
    {{ if .Labels.addr -}}
    - <b>Link: </b>https://testnet.tonviewer.com/{{ .Labels.addr }}
    {{ end -}}
    {{ end -}}
    {{ end -}}
    {{ end -}}