env:
  GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  enabled: true
  extraPaths: []
  labels: {}
  path: /dashboard/
  pathType: ImplementationSpecific
persistence:
  enabled: true
  size: 1Gi
rbac:
  namespaced: true
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true
        editable: true
      - name: VictoriaLogs
        type: victoriametrics-logs-datasource
        url: http://vmlogs-victoria-logs-single-server:9428
        access: proxy
        isDefault: false
        editable: true
      - name: Infinity
        type: yesoreyeram-infinity-datasource
        access: proxy
        isDefault: false
        editable: true
plugins:
  - "victoriametrics-logs-datasource"
  - "yesoreyeram-infinity-datasource"
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    provider:
      allowUiUpdates: true
envFromSecrets:
  - name: grafana-google-oauth-creds
grafana.ini:
  auth:
    oauth_auto_login: false
    disable_login_form: false
    disable_signout_menu: false
  auth.google:
    enabled: true
    client_id: ${GF_AUTH_GOOGLE_CLIENT_ID}
    client_secret: ${GF_AUTH_GOOGLE_CLIENT_SECRET}
    enabled: true
  unified_alerting:
    enabled: true
  users:
    auto_assign_org_role: Editor
    viewers_can_edit: false
  security:
    allow_embedding: true