env:
  GF_SERVER_DOMAIN: ton-teleport.sand.rsquad.solutions
  GF_SERVER_ROOT_URL: https://ton-teleport.sand.rsquad.solutions/dashboard/
ingress:
  hosts:
    - ton-teleport.sand.rsquad.solutions
  tls:
    - hosts:
        - ton-teleport.sand.rsquad.solutions
      secretName: ton-teleport.sand.rsquad.solutions-tls