{
 "title": "Statistics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "tgBtcBurned",
    "query": "select \n  sum((cast (b.amount as numeric)) / 100000000)::numeric(20,8) as total_burned\nfrom burns as b\njoin pegouts as p on p.id = b.pegout_burn where p.status = 'CONFIRMED'"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Mints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as row_count FROM mints;"
    }
   ]
  },
  {
   "title": "Total Burns",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as row_count FROM burns;"
    }
   ]
  },
  {
   "title": "tgBTC Current Supply",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 },
    { "panelId": 4 }
   ]
  },
  {
   "title": "tgBTC Minted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  sum((cast(amount as numeric)) / 100000000)::numeric(20,8) as total_minted \nfrom mints where status = 'SUCCESS'"
    }
   ]
  },
  {
   "title": "tgBTC Burned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  sum((cast (b.amount as numeric)) / 100000000)::numeric(20,8) as total_burned\nfrom burns as b\njoin pegouts as p on p.id = b.pegout_burn where p.status = 'CONFIRMED'"
    }
   ]
  },
  {
   "title": "tgBTC Flow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select cast(amount as numeric) / 100000000 as minted, created_at from mints\nwhere $__timeFilter(created_at) and status = 'SUCCESS'\norder by created_at"
    },
    {
     "rawSql": "select \n  cast (b.amount as numeric) / 100000000 as burned,\n  tt.created_at\nfrom burns as b\njoin ton_txes as tt on tt.id = b.ton_tx_burn\njoin pegouts as p on p.id = b.pegout_burn where p.status = 'CONFIRMED'"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "WITH date_series AS (\n  SELECT generate_series(\n    DATE_TRUNC('day', $__timeFrom()::timestamp),\n    DATE_TRUNC('day', $__timeTo()::timestamp),\n    '1 day'::interval\n  ) AS day\n),\ndaily_counts AS (\n  SELECT\n    DATE_TRUNC('day', created_at) AS day,\n    COUNT(*) AS count\n  FROM mints\n  WHERE $__timeFilter(created_at) AND status = 'SUCCESS'\n  GROUP BY 1\n)\nSELECT\n  ds.day AS time,\n  COALESCE(dc.count, 0) AS \"Mints\"\nFROM date_series ds\nLEFT JOIN daily_counts dc ON ds.day = dc.day\nORDER BY 1;"
    },
    {
     "rawSql": "WITH date_series AS (\n  SELECT generate_series(\n    DATE_TRUNC('day', $__timeFrom()::timestamp),\n    DATE_TRUNC('day', $__timeTo()::timestamp),\n    '1 day'::interval\n  ) AS day\n),\ndaily_counts AS (\n  SELECT\n    DATE_TRUNC('day', created_at) AS day,\n    COUNT(*) AS count\n  FROM burns as b\n  join ton_txes as tt on tt.id = ton_tx_burn\n  join pegouts as p on p.id = b.pegout_burn\n  WHERE $__timeFilter(created_at) and p.status = 'CONFIRMED'\n  GROUP BY 1\n)\nSELECT\n  ds.day AS time,\n  COALESCE(dc.count, 0) AS \"Burns\"\nFROM date_series ds\nLEFT JOIN daily_counts dc ON ds.day = dc.day\nORDER BY 1;"
    }
   ]
  }
 ]
}