// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Statistics struct {
	TotalMints               int    `json:"totalMints"`
	TotalBurns               int    `json:"totalBurns"`
	TotalTgBTCMinted         string `json:"totalTgBTCMinted"`
	TotalTgBTCBurned         string `json:"totalTgBTCBurned"`
	TgBTCAmount              string `json:"tgBTCAmount"`
	UniqueMintReceiversCount int    `json:"uniqueMintReceiversCount"`
	UniqueBurnSendersCount   int    `json:"uniqueBurnSendersCount"`
}
