package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"

	"entgo.io/contrib/entgql"
	"github.com/rsquad/ton-teleport-btc-periphery/indexer/internal/ent/generated"
)

// Node is the resolver for the node field.
func (r *queryResolver) Node(ctx context.Context, id int) (generated.Noder, error) {
	return r.repo.Noder(ctx, id)
}

// Nodes is the resolver for the nodes field.
func (r *queryResolver) Nodes(ctx context.Context, ids []int) ([]generated.Noder, error) {
	return r.repo.Noders(ctx, ids)
}

// Burns is the resolver for the burns field.
func (r *queryResolver) Burns(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *generated.BurnWhereInput) (*generated.BurnConnection, error) {
	return r.repo.Burn.Query().
		Paginate(ctx, after, first, before, last, generated.WithBurnFilter(where.Filter))
}

// InternalKeys is the resolver for the internalKeys field.
func (r *queryResolver) InternalKeys(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *generated.InternalKeyWhereInput) (*generated.InternalKeyConnection, error) {
	return r.repo.InternalKey.Query().
		Paginate(ctx, after, first, before, last, generated.WithInternalKeyFilter(where.Filter))
}

// Mints is the resolver for the mints field.
func (r *queryResolver) Mints(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *generated.MintWhereInput) (*generated.MintConnection, error) {
	return r.repo.Mint.Query().
		Paginate(ctx, after, first, before, last, generated.WithMintFilter(where.Filter))
}

// Pegins is the resolver for the pegins field.
func (r *queryResolver) Pegins(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *generated.PeginWhereInput) (*generated.PeginConnection, error) {
	return r.repo.Pegin.Query().
		Paginate(ctx, after, first, before, last, generated.WithPeginFilter(where.Filter))
}

// Pegouts is the resolver for the pegouts field.
func (r *queryResolver) Pegouts(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *generated.PegoutWhereInput) (*generated.PegoutConnection, error) {
	return r.repo.Pegout.Query().
		Paginate(ctx, after, first, before, last, generated.WithPegoutFilter(where.Filter))
}

// Reinits is the resolver for the reinits field.
func (r *queryResolver) Reinits(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *generated.ReinitWhereInput) (*generated.ReinitConnection, error) {
	return r.repo.Reinit.Query().
		Paginate(ctx, after, first, before, last, generated.WithReinitFilter(where.Filter))
}

// TonTxes is the resolver for the tonTxes field.
func (r *queryResolver) TonTxes(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *generated.TonTxWhereInput) (*generated.TonTxConnection, error) {
	return r.repo.TonTx.Query().
		Paginate(ctx, after, first, before, last, generated.WithTonTxFilter(where.Filter))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) StateDkGs(ctx context.Context) ([]*generated.StateDKG, error) {
	panic(fmt.Errorf("not implemented: StateDkGs - stateDkGs"))
}
*/
