package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"fmt"
	"math/big"

	"github.com/rsquad/ton-teleport-btc-periphery/indexer/internal/ent/generated"
)

// CreatePegin is the resolver for the createPegin field.
func (r *mutationResolver) CreatePegin(ctx context.Context, input generated.CreatePeginInput) (*generated.Pegin, error) {
	repo := generated.FromContext(ctx)

	peginExists, err := r.peginManager.PeginExists(input.BitcoinTxId)
	if peginExists {
		return nil, fmt.Errorf("pegin with the same bitcoin tx id already exists: %w", err)
	}

	internalKeyExists, err := r.peginManager.InternalKeyExists(*input.InternalKey)
	if !internalKeyExists {
		return nil, err
	}

	bitcoinTxExists, _, err := r.peginManager.BitcoinTxExists(input.BitcoinTxId)
	if !bitcoinTxExists {
		return nil, err
	}

	mint, err := repo.Mint.Create().Save(ctx)
	if err != nil {
		return nil, err
	}

	return repo.Pegin.Create().SetInput(input).SetMint(mint).Save(ctx)
}

// Statistics is the resolver for the statistics field.
func (r *queryResolver) Statistics(ctx context.Context) (*Statistics, error) {
	mints, err := r.repo.Mint.Query().All(ctx)
	if err != nil {
		return nil, err
	}

	totalMintAmount := big.NewInt(0)
	uniqueMintReceivers := make(map[string]struct{})
	for _, mint := range mints {
		amount := new(big.Int)
		amount, ok := amount.SetString(mint.Amount, 10)
		if !ok {
			return nil, fmt.Errorf("invalid amount: %s", mint.Amount)
		}
		totalMintAmount.Add(totalMintAmount, amount)
		uniqueMintReceivers[mint.Edges.Pegin.ReceiverAddr] = struct{}{}
	}

	uniqueMintReceiversCount := len(uniqueMintReceivers)

	burns, err := r.repo.Burn.Query().All(ctx)
	if err != nil {
		return nil, err
	}

	totalBurnAmount := big.NewInt(0)
	uniqueBurnSenders := make(map[string]struct{})
	for _, burn := range burns {
		amount := new(big.Int)
		amount, ok := amount.SetString(burn.Amount, 10)
		if !ok {
			return nil, fmt.Errorf("invalid amount: %s", burn.Amount)
		}
		totalBurnAmount.Add(totalBurnAmount, amount)
		uniqueBurnSenders[burn.SenderAddr] = struct{}{}
	}

	uniqueBurnSendersCount := len(uniqueBurnSenders)

	return &Statistics{
		TotalMints:               len(mints),
		TotalBurns:               len(burns),
		TotalTgBTCMinted:         totalMintAmount.String(),
		TotalTgBTCBurned:         totalBurnAmount.String(),
		TgBTCAmount:              totalMintAmount.Sub(totalMintAmount, totalBurnAmount).String(),
		UniqueMintReceiversCount: uniqueMintReceiversCount,
		UniqueBurnSendersCount:   uniqueBurnSendersCount,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
