package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.57

import (
	"context"
	"encoding/hex"
	"errors"
	"fmt"
	"log"
	"math/big"
	"time"

	btcec "github.com/btcsuite/btcd/btcec/v2"
	"github.com/btcsuite/btcd/btcec/v2/schnorr"
	"github.com/btcsuite/btcd/btcjson"
	"github.com/btcsuite/btcd/btcutil"
	ent "github.com/rsquad/ton-teleport-btc-periphery/indexer/internal/ent/generated"
	entburn "github.com/rsquad/ton-teleport-btc-periphery/indexer/internal/ent/generated/burn"
	entinternalkey "github.com/rsquad/ton-teleport-btc-periphery/indexer/internal/ent/generated/internalkey"
	entmint "github.com/rsquad/ton-teleport-btc-periphery/indexer/internal/ent/generated/mint"
	entpegin "github.com/rsquad/ton-teleport-btc-periphery/indexer/internal/ent/generated/pegin"
	entpegout "github.com/rsquad/ton-teleport-btc-periphery/indexer/internal/ent/generated/pegout"
	"github.com/rsquad/ton-teleport-btc-periphery/indexer/internal/peginutils"
	"github.com/rsquad/ton-teleport-btc-periphery/lib/pkg/bitcoin"
	"github.com/rsquad/ton-teleport-btc-periphery/lib/pkg/ton/credscontract"
	"github.com/xssnick/tonutils-go/address"
)

// CreatePegin is the resolver for the createPegin field.
func (r *mutationResolver) CreatePegin(ctx context.Context, input ent.CreatePeginInput) (*ent.Pegin, error) {
	repo := ent.FromContext(ctx)

	// 0. Check if Pegin already exists for this Bitcoin Tx
	existingPegin, err := repo.Pegin.
		Query().
		Where(entpegin.BitcoinTxIDEQ(input.BitcoinTxID)).
		Only(ctx)
	if err == nil {
		return existingPegin, nil
	}

	// 1. Parse Receiver Address
	receiverAddr, err := address.ParseRawAddr(input.ReceiverAddr)
	if err != nil {
		return nil, fmt.Errorf("invalid receiver address: %w", err)
	}

	// 2. Fetch Bitcoin Transaction
	bitcoinTxExists, bitcoinTx, err := r.bitcoinTxExists(input.BitcoinTxID)
	if err != nil {
		return nil, fmt.Errorf("failed to check bitcoin tx: %w", err)
	}
	if !bitcoinTxExists {
		return nil, fmt.Errorf("bitcoin tx not found: %s", input.BitcoinTxID)
	}

	// 3. Fetch Teleport Contract Storage for CSV locks and limits
	teleportContractStorage, err := r.teleportContract.GetStorage(nil) // Use ctx?
	if err != nil {
		return nil, fmt.Errorf("failed to get teleport contract storage: %w", err)
	}
	possibleCvsLocks := []uint32{teleportContractStorage.CsvLock, 36, 29}

	// 4. Prepare list of potential Internal Keys
	var internalKeys []*btcec.PublicKey
	var internalKeyModels []*ent.InternalKey
	var targetInternalKeyModel *ent.InternalKey // The model corresponding to the key found in the tx

	if input.InternalKey != nil && *input.InternalKey != "" {
		internalKeyBytes, err := hex.DecodeString(*input.InternalKey)
		if err != nil {
			return nil, fmt.Errorf("invalid provided internal key hex: %w", err)
		}
		parsedKey, err := schnorr.ParsePubKey(internalKeyBytes)
		if err != nil {
			return nil, fmt.Errorf("failed to parse provided internal key: %w", err)
		}
		internalKeys = append(internalKeys, parsedKey)

		// Find the specific model for the provided key
		model, err := r.findInternalKey(ctx, *input.InternalKey)
		if err != nil {
			// Even if provided, it must exist in our DB
			return nil, fmt.Errorf("provided internal key %s not found in indexer DB: %w", *input.InternalKey, err)
		}
		internalKeyModels = append(internalKeyModels, model) // Add to list for consistency, though we'll likely use targetInternalKeyModel directly
		targetInternalKeyModel = model                       // Set directly since it was provided
	} else {
		// Fetch all internal keys from DB
		allModels, err := repo.InternalKey.Query().
			Order(ent.Desc(entinternalkey.FieldCompletedAt)).
			Limit(100).
			All(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to query latest 100 internal keys: %w", err)
		}
		if len(allModels) == 0 {
			return nil, fmt.Errorf("no internal keys found in the database")
		}
		internalKeyModels = allModels // Store all models
		for _, model := range allModels {
			internalKeyBytes, err := hex.DecodeString(model.Key)
			if err != nil {
				// Log this error? Skip this key?
				continue // Skip invalid keys stored in DB
			}
			parsedKey, err := schnorr.ParsePubKey(internalKeyBytes)
			if err != nil {
				// Log this error? Skip this key?
				continue // Skip invalid keys stored in DB
			}
			internalKeys = append(internalKeys, parsedKey)
		}
		if len(internalKeys) == 0 {
			return nil, fmt.Errorf("no valid internal keys could be parsed from database")
		}
	}

	// 5. Prepare list of potential Recovery Keys
	var recoveryKeys []*btcec.PublicKey
	if input.RecoveryKey != nil && *input.RecoveryKey != "" {
		recoveryKeyBytes, err := hex.DecodeString(*input.RecoveryKey)
		if err != nil {
			return nil, fmt.Errorf("invalid provided recovery key hex: %w", err)
		}
		parsedKey, err := schnorr.ParsePubKey(recoveryKeyBytes)
		if err != nil {
			return nil, fmt.Errorf("failed to parse provided recovery key: %w", err)
		}
		recoveryKeys = append(recoveryKeys, parsedKey)
	} else {
		// Fetch recovery keys from Creds Contract
		credsContract, err := credscontract.NewFromStateInit(
			r.tonClient,
			&credscontract.StateInit{
				Code: credscontract.GetCode(),
				InitData: &credscontract.InitData{
					Owner: receiverAddr, // Use parsed receiver address
				},
			},
		)
		if err != nil {
			return nil, fmt.Errorf("failed to init creds contract: %w", err)
		}

		credsContractStorage, err := credsContract.GetStorage(ctx, nil) // Use ctx?
		if err != nil {
			// If storage can't be retrieved, we can't get recovery keys
			return nil, fmt.Errorf("failed to get creds contract storage for receiver %s: %w", input.ReceiverAddr, err)
		}

		// Extract keys from the map[string][]byte structure
		if len(credsContractStorage.Creds) == 0 {
			return nil, fmt.Errorf("no recovery keys found in creds contract storage for receiver %s", input.ReceiverAddr)
		}

		for keyStr := range credsContractStorage.Creds {
			keyBytes, err := hex.DecodeString(keyStr)
			if err != nil {
				fmt.Printf("Warning: Failed to decode recovery key hex string '%s' from creds contract for receiver %s: %v\n", keyStr, input.ReceiverAddr, err)
				continue
			}

			if len(keyBytes) == 0 {
				// Log or handle empty key bytes?
				continue
			}
			parsedKey, err := schnorr.ParsePubKey(keyBytes)
			if err != nil {
				// Log? Skip?
				fmt.Printf("Warning: Failed to parse recovery key from creds contract for receiver %s: %v\n", input.ReceiverAddr, err)
				continue
			}
			recoveryKeys = append(recoveryKeys, parsedKey)
		}
		if len(recoveryKeys) == 0 {
			return nil, fmt.Errorf("no valid recovery keys could be parsed from creds contract storage for receiver %s", input.ReceiverAddr)
		}
	}

	// 6. Iterate through all combinations to find the matching output
	var foundInternalKey *btcec.PublicKey
	var foundRecoveryKey *btcec.PublicKey
	var foundVout *btcjson.Vout

searchLoop:
	for _, ik := range internalKeys {
		for _, rk := range recoveryKeys {
			for _, cvsLock := range possibleCvsLocks {
				peginBitcoinScript, err := peginutils.CalcPeginBitcoinScript(ik, rk, receiverAddr, cvsLock)
				if err != nil {
					// Log? Should this error be fatal or just skip combination?
					fmt.Printf("Warning: Failed to calculate pegin address for combination: %v\n", err)
					continue // Skip this combination
				}
				if addrFound, voutFound := bitcoin.TxContainsOutWithScript(bitcoinTx, peginBitcoinScript); addrFound {
					foundInternalKey = ik
					foundRecoveryKey = rk
					foundVout = voutFound
					break searchLoop // Found the matching output
				}
			}
		}
	}

	// 7. Check if a match was found
	if foundVout == nil {
		// Construct a more informative error message
		errMsg := fmt.Sprintf("[PEGIN_MATCH_NOT_FOUND] no matching pegin output found in bitcoin tx %s for receiver %s", input.BitcoinTxID, input.ReceiverAddr)
		if input.InternalKey != nil {
			errMsg += fmt.Sprintf(" with provided internal key %s", *input.InternalKey)
		} else {
			errMsg += fmt.Sprintf(" using %d possible internal keys", len(internalKeys))
		}
		if input.RecoveryKey != nil {
			errMsg += fmt.Sprintf(" and provided recovery key %s", *input.RecoveryKey)
		} else {
			errMsg += fmt.Sprintf(" and %d possible recovery keys from creds contract", len(recoveryKeys))
		}
		return nil, errors.New(errMsg)
	}

	// 8. Determine the Internal Key Model corresponding to the found key
	// If internal key was provided, targetInternalKeyModel is already set
	if targetInternalKeyModel == nil {
		// Find the model matching foundInternalKey
		// We need to compare the X-coordinate hex string with the key stored in the DB.
		foundInternalKeyBytesCompressed := foundInternalKey.SerializeCompressed() // 33 bytes (prefix + X)
		if len(foundInternalKeyBytesCompressed) != 33 {
			// Maybe add logging here if this happens in production? For now, just error.
			return nil, fmt.Errorf("internal inconsistency: compressed key has unexpected length %d", len(foundInternalKeyBytesCompressed))
		}
		foundInternalKeyXBytes := foundInternalKeyBytesCompressed[1:]      // 32 bytes (X-coordinate)
		foundInternalKeyXHex := hex.EncodeToString(foundInternalKeyXBytes) // 64 hex chars (X-coordinate)

		foundMatch := false
		for _, model := range internalKeyModels {
			// Compare model.Key (64 hex chars from DB) with foundInternalKeyXHex (64 hex chars derived from found key)
			if model.Key == foundInternalKeyXHex {
				targetInternalKeyModel = model
				foundMatch = true
				break
			}
		}
		// This should ideally not happen if foundInternalKey came from internalKeyModels
		if !foundMatch {
			log.Printf("[ERROR] Internal inconsistency: Could not find DB model for the matched internal key X-coordinate hex %s", foundInternalKeyXHex)
			return nil, fmt.Errorf("internal inconsistency: could not find DB model for the matched internal key X-coordinate hex %s", foundInternalKeyXHex)
		}
	}

	// 9. Calculate Amount
	amount, err := btcutil.NewAmount(foundVout.Value)
	if err != nil {
		return nil, fmt.Errorf("failed to convert vout value %f to btcutil.Amount: %w", foundVout.Value, err)
	}

	// 10. Prepare Mint creation
	mintCreateAt := time.Now()
	if bitcoinTx.Time != 0 {
		mintCreateAt = time.Unix(bitcoinTx.Time, 0)
	}

	mintCreate := repo.Mint.Create().
		SetAmount(fmt.Sprintf("%d", amount)). // Store as satoshis string
		SetCreatedAt(mintCreateAt)

	// 11. Apply Mint status checks (Refund conditions)
	// Check 1: Minimum Pegin Amount
	if amount.ToUnit(btcutil.AmountSatoshi) < float64(teleportContractStorage.Limits.MinPeginAmount) {
		mintCreate.SetStatus(entmint.StatusRefund)
	}

	// Check 2: Internal Key Rotation (using targetInternalKeyModel)
	latestInternalKey, err := repo.InternalKey.Query().
		Order(ent.Desc(entinternalkey.FieldCompletedAt)).
		First(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to query latest internal key for rotation check: %w", err)
	}

	// Ensure the target key (the one used in the successful pegin) is the latest completed one
	if targetInternalKeyModel.CompletedAt.IsZero() || !targetInternalKeyModel.CompletedAt.Equal(latestInternalKey.CompletedAt) {
		mintCreate.SetStatus(entmint.StatusRefund)
	}

	// 12. Save Mint
	mint, err := mintCreate.Save(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to save mint record: %w", err)
	}

	// 13. Save Pegin
	// We need to ensure the Pegin record stores the keys that were actually used.
	finalInternalKeyHex := hex.EncodeToString(foundInternalKey.SerializeCompressed()[1:])
	finalRecoveryKeyHex := hex.EncodeToString(foundRecoveryKey.SerializeCompressed()[1:])

	return repo.Pegin.Create().
		SetBitcoinTxID(input.BitcoinTxID).   // Use original input TxID
		SetReceiverAddr(input.ReceiverAddr). // Use original input ReceiverAddr
		SetInternalKey(finalInternalKeyHex). // Use the key found in the tx
		SetRecoveryKey(finalRecoveryKeyHex). // Use the key found in the tx
		SetMint(mint).
		SetVoutIndex(int(foundVout.N)).
		Save(ctx)
}

// Statistics is the resolver for the statistics field.
func (r *queryResolver) Statistics(ctx context.Context) (*Statistics, error) {
	mints, err := r.repo.Mint.
		Query().
		WithPegin().
		Where(entmint.StatusIn(entmint.StatusSuccess)).
		All(ctx)
	if err != nil {
		return nil, err
	}

	totalMintAmount := big.NewInt(0)
	uniqueMintReceivers := make(map[string]struct{})
	for _, mint := range mints {
		amount := new(big.Int)
		amount, ok := amount.SetString(mint.Amount, 10)
		if !ok {
			return nil, fmt.Errorf("invalid amount: %s", mint.Amount)
		}
		totalMintAmount.Add(totalMintAmount, amount)
		uniqueMintReceivers[mint.Edges.Pegin.ReceiverAddr] = struct{}{}
	}

	uniqueMintReceiversCount := len(uniqueMintReceivers)

	burns, err := r.repo.Burn.Query().
		Where(entburn.HasPegoutWith(entpegout.StatusIn(entpegout.StatusConfirmed))).
		All(ctx)
	if err != nil {
		return nil, err
	}

	totalBurnAmount := big.NewInt(0)
	uniqueBurnSenders := make(map[string]struct{})
	for _, burn := range burns {
		amount := new(big.Int)
		amount, ok := amount.SetString(burn.Amount, 10)
		if !ok {
			return nil, fmt.Errorf("invalid amount: %s", burn.Amount)
		}
		totalBurnAmount.Add(totalBurnAmount, amount)
		uniqueBurnSenders[burn.SenderAddr] = struct{}{}
	}

	uniqueBurnSendersCount := len(uniqueBurnSenders)

	return &Statistics{
		TotalMints:               len(mints),
		TotalBurns:               len(burns),
		TotalTgBTCMinted:         totalMintAmount.String(),
		TotalTgBTCBurned:         totalBurnAmount.String(),
		TgBTCAmount:              totalMintAmount.Sub(totalMintAmount, totalBurnAmount).String(),
		UniqueMintReceiversCount: uniqueMintReceiversCount,
		UniqueBurnSendersCount:   uniqueBurnSendersCount,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
