// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package coordinator

import (
	"github.com/rsquad/ton-teleport-btc-periphery/lib/pkg/ton/signer"
	"github.com/xssnick/tonutils-go/address"
	"github.com/xssnick/tonutils-go/tlb"
	tonutils "github.com/xssnick/tonutils-go/ton"
	"sync"
)

// Ensure, that CoordinatorContractMock does implement CoordinatorContract.
// If this is not the case, regenerate this file with moq.
var _ CoordinatorContract = &CoordinatorContractMock{}

// CoordinatorContractMock is a mock implementation of CoordinatorContract.
//
//	func TestSomethingThatUsesCoordinatorContract(t *testing.T) {
//
//		// make and configure a mocked CoordinatorContract
//		mockedCoordinatorContract := &CoordinatorContractMock{
//			ConnectSignerFunc: func(signerMoqParam signer.Signer)  {
//				panic("mock out the ConnectSigner method")
//			},
//			GetAddrFunc: func() *address.Address {
//				panic("mock out the GetAddr method")
//			},
//			GetDkgFunc: func(block *tonutils.BlockIDExt) (*DKG, error) {
//				panic("mock out the GetDkg method")
//			},
//			GetPrevDKGFunc: func() (*DKG, error) {
//				panic("mock out the GetPrevDKG method")
//			},
//			GetUnsignedPegoutsFunc: func() ([]PegoutRecord, error) {
//				panic("mock out the GetUnsignedPegouts method")
//			},
//			SendCommitmentsFunc: func(pegoutID uint64, validatorIdx uint16, commitments []byte) (*tlb.Transaction, error) {
//				panic("mock out the SendCommitments method")
//			},
//			SendDKGClaimFunc: func(validatorIdx uint16, dkgUntil int64, culpritIdx uint16) (*tlb.Transaction, error) {
//				panic("mock out the SendDKGClaim method")
//			},
//			SendPubkeyPackageFunc: func(validatorIdx uint16, dkgUntil int64, sessionPublicKey []byte, pubkeyPackage []byte) (*tlb.Transaction, error) {
//				panic("mock out the SendPubkeyPackage method")
//			},
//			SendResetPegoutSigningFunc: func(pegoutID uint64, validatorIdx uint16) (*tlb.Transaction, error) {
//				panic("mock out the SendResetPegoutSigning method")
//			},
//			SendRound1Func: func(validatorIdx uint16, dkgUntil int64, round1Package []byte, r2PublicX25519 *[32]byte) (*tlb.Transaction, error) {
//				panic("mock out the SendRound1 method")
//			},
//			SendRound2Func: func(validatorIdx uint16, dkgUntil int64, round2Packages []byte) (*tlb.Transaction, error) {
//				panic("mock out the SendRound2 method")
//			},
//			SendSignaturesFunc: func(pegoutID uint64, validatorIdx uint16, signatures [][]byte) (*tlb.Transaction, error) {
//				panic("mock out the SendSignatures method")
//			},
//			SendSigningClaimFunc: func(pegoutID uint64, validatorIdx uint16, culpritIdx uint16) (*tlb.Transaction, error) {
//				panic("mock out the SendSigningClaim method")
//			},
//			SendSigningShareFunc: func(pegoutID uint64, validatorIdx uint16, signingShares [][]byte) (*tlb.Transaction, error) {
//				panic("mock out the SendSigningShare method")
//			},
//			SendStartDKGFunc: func() (*tlb.Transaction, error) {
//				panic("mock out the SendStartDKG method")
//			},
//		}
//
//		// use mockedCoordinatorContract in code that requires CoordinatorContract
//		// and then make assertions.
//
//	}
type CoordinatorContractMock struct {
	// ConnectSignerFunc mocks the ConnectSigner method.
	ConnectSignerFunc func(signerMoqParam signer.Signer)

	// GetAddrFunc mocks the GetAddr method.
	GetAddrFunc func() *address.Address

	// GetDkgFunc mocks the GetDkg method.
	GetDkgFunc func(block *tonutils.BlockIDExt) (*DKG, error)

	// GetPrevDKGFunc mocks the GetPrevDKG method.
	GetPrevDKGFunc func() (*DKG, error)

	// GetUnsignedPegoutsFunc mocks the GetUnsignedPegouts method.
	GetUnsignedPegoutsFunc func() ([]PegoutRecord, error)

	// SendCommitmentsFunc mocks the SendCommitments method.
	SendCommitmentsFunc func(pegoutID uint64, validatorIdx uint16, commitments []byte) (*tlb.Transaction, error)

	// SendDKGClaimFunc mocks the SendDKGClaim method.
	SendDKGClaimFunc func(validatorIdx uint16, dkgUntil int64, culpritIdx uint16) (*tlb.Transaction, error)

	// SendPubkeyPackageFunc mocks the SendPubkeyPackage method.
	SendPubkeyPackageFunc func(validatorIdx uint16, dkgUntil int64, sessionPublicKey []byte, pubkeyPackage []byte) (*tlb.Transaction, error)

	// SendResetPegoutSigningFunc mocks the SendResetPegoutSigning method.
	SendResetPegoutSigningFunc func(pegoutID uint64, validatorIdx uint16) (*tlb.Transaction, error)

	// SendRound1Func mocks the SendRound1 method.
	SendRound1Func func(validatorIdx uint16, dkgUntil int64, round1Package []byte, r2PublicX25519 *[32]byte) (*tlb.Transaction, error)

	// SendRound2Func mocks the SendRound2 method.
	SendRound2Func func(validatorIdx uint16, dkgUntil int64, round2Packages []byte) (*tlb.Transaction, error)

	// SendSignaturesFunc mocks the SendSignatures method.
	SendSignaturesFunc func(pegoutID uint64, validatorIdx uint16, signatures [][]byte) (*tlb.Transaction, error)

	// SendSigningClaimFunc mocks the SendSigningClaim method.
	SendSigningClaimFunc func(pegoutID uint64, validatorIdx uint16, culpritIdx uint16) (*tlb.Transaction, error)

	// SendSigningShareFunc mocks the SendSigningShare method.
	SendSigningShareFunc func(pegoutID uint64, validatorIdx uint16, signingShares [][]byte) (*tlb.Transaction, error)

	// SendStartDKGFunc mocks the SendStartDKG method.
	SendStartDKGFunc func() (*tlb.Transaction, error)

	// calls tracks calls to the methods.
	calls struct {
		// ConnectSigner holds details about calls to the ConnectSigner method.
		ConnectSigner []struct {
			// SignerMoqParam is the signerMoqParam argument value.
			SignerMoqParam signer.Signer
		}
		// GetAddr holds details about calls to the GetAddr method.
		GetAddr []struct {
		}
		// GetDkg holds details about calls to the GetDkg method.
		GetDkg []struct {
			// Block is the block argument value.
			Block *tonutils.BlockIDExt
		}
		// GetPrevDKG holds details about calls to the GetPrevDKG method.
		GetPrevDKG []struct {
		}
		// GetUnsignedPegouts holds details about calls to the GetUnsignedPegouts method.
		GetUnsignedPegouts []struct {
		}
		// SendCommitments holds details about calls to the SendCommitments method.
		SendCommitments []struct {
			// PegoutID is the pegoutID argument value.
			PegoutID uint64
			// ValidatorIdx is the validatorIdx argument value.
			ValidatorIdx uint16
			// Commitments is the commitments argument value.
			Commitments []byte
		}
		// SendDKGClaim holds details about calls to the SendDKGClaim method.
		SendDKGClaim []struct {
			// ValidatorIdx is the validatorIdx argument value.
			ValidatorIdx uint16
			// DkgUntil is the dkgUntil argument value.
			DkgUntil int64
			// CulpritIdx is the culpritIdx argument value.
			CulpritIdx uint16
		}
		// SendPubkeyPackage holds details about calls to the SendPubkeyPackage method.
		SendPubkeyPackage []struct {
			// ValidatorIdx is the validatorIdx argument value.
			ValidatorIdx uint16
			// DkgUntil is the dkgUntil argument value.
			DkgUntil int64
			// SessionPublicKey is the sessionPublicKey argument value.
			SessionPublicKey []byte
			// PubkeyPackage is the pubkeyPackage argument value.
			PubkeyPackage []byte
		}
		// SendResetPegoutSigning holds details about calls to the SendResetPegoutSigning method.
		SendResetPegoutSigning []struct {
			// PegoutID is the pegoutID argument value.
			PegoutID uint64
			// ValidatorIdx is the validatorIdx argument value.
			ValidatorIdx uint16
		}
		// SendRound1 holds details about calls to the SendRound1 method.
		SendRound1 []struct {
			// ValidatorIdx is the validatorIdx argument value.
			ValidatorIdx uint16
			// DkgUntil is the dkgUntil argument value.
			DkgUntil int64
			// Round1Package is the round1Package argument value.
			Round1Package []byte
			// R2PublicX25519 is the r2PublicX25519 argument value.
			R2PublicX25519 *[32]byte
		}
		// SendRound2 holds details about calls to the SendRound2 method.
		SendRound2 []struct {
			// ValidatorIdx is the validatorIdx argument value.
			ValidatorIdx uint16
			// DkgUntil is the dkgUntil argument value.
			DkgUntil int64
			// Round2Packages is the round2Packages argument value.
			Round2Packages []byte
		}
		// SendSignatures holds details about calls to the SendSignatures method.
		SendSignatures []struct {
			// PegoutID is the pegoutID argument value.
			PegoutID uint64
			// ValidatorIdx is the validatorIdx argument value.
			ValidatorIdx uint16
			// Signatures is the signatures argument value.
			Signatures [][]byte
		}
		// SendSigningClaim holds details about calls to the SendSigningClaim method.
		SendSigningClaim []struct {
			// PegoutID is the pegoutID argument value.
			PegoutID uint64
			// ValidatorIdx is the validatorIdx argument value.
			ValidatorIdx uint16
			// CulpritIdx is the culpritIdx argument value.
			CulpritIdx uint16
		}
		// SendSigningShare holds details about calls to the SendSigningShare method.
		SendSigningShare []struct {
			// PegoutID is the pegoutID argument value.
			PegoutID uint64
			// ValidatorIdx is the validatorIdx argument value.
			ValidatorIdx uint16
			// SigningShares is the signingShares argument value.
			SigningShares [][]byte
		}
		// SendStartDKG holds details about calls to the SendStartDKG method.
		SendStartDKG []struct {
		}
	}
	lockConnectSigner          sync.RWMutex
	lockGetAddr                sync.RWMutex
	lockGetDkg                 sync.RWMutex
	lockGetPrevDKG             sync.RWMutex
	lockGetUnsignedPegouts     sync.RWMutex
	lockSendCommitments        sync.RWMutex
	lockSendDKGClaim           sync.RWMutex
	lockSendPubkeyPackage      sync.RWMutex
	lockSendResetPegoutSigning sync.RWMutex
	lockSendRound1             sync.RWMutex
	lockSendRound2             sync.RWMutex
	lockSendSignatures         sync.RWMutex
	lockSendSigningClaim       sync.RWMutex
	lockSendSigningShare       sync.RWMutex
	lockSendStartDKG           sync.RWMutex
}

// ConnectSigner calls ConnectSignerFunc.
func (mock *CoordinatorContractMock) ConnectSigner(signerMoqParam signer.Signer) {
	if mock.ConnectSignerFunc == nil {
		panic("CoordinatorContractMock.ConnectSignerFunc: method is nil but CoordinatorContract.ConnectSigner was just called")
	}
	callInfo := struct {
		SignerMoqParam signer.Signer
	}{
		SignerMoqParam: signerMoqParam,
	}
	mock.lockConnectSigner.Lock()
	mock.calls.ConnectSigner = append(mock.calls.ConnectSigner, callInfo)
	mock.lockConnectSigner.Unlock()
	mock.ConnectSignerFunc(signerMoqParam)
}

// ConnectSignerCalls gets all the calls that were made to ConnectSigner.
// Check the length with:
//
//	len(mockedCoordinatorContract.ConnectSignerCalls())
func (mock *CoordinatorContractMock) ConnectSignerCalls() []struct {
	SignerMoqParam signer.Signer
} {
	var calls []struct {
		SignerMoqParam signer.Signer
	}
	mock.lockConnectSigner.RLock()
	calls = mock.calls.ConnectSigner
	mock.lockConnectSigner.RUnlock()
	return calls
}

// GetAddr calls GetAddrFunc.
func (mock *CoordinatorContractMock) GetAddr() *address.Address {
	if mock.GetAddrFunc == nil {
		panic("CoordinatorContractMock.GetAddrFunc: method is nil but CoordinatorContract.GetAddr was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetAddr.Lock()
	mock.calls.GetAddr = append(mock.calls.GetAddr, callInfo)
	mock.lockGetAddr.Unlock()
	return mock.GetAddrFunc()
}

// GetAddrCalls gets all the calls that were made to GetAddr.
// Check the length with:
//
//	len(mockedCoordinatorContract.GetAddrCalls())
func (mock *CoordinatorContractMock) GetAddrCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetAddr.RLock()
	calls = mock.calls.GetAddr
	mock.lockGetAddr.RUnlock()
	return calls
}

// GetDkg calls GetDkgFunc.
func (mock *CoordinatorContractMock) GetDkg(block *tonutils.BlockIDExt) (*DKG, error) {
	if mock.GetDkgFunc == nil {
		panic("CoordinatorContractMock.GetDkgFunc: method is nil but CoordinatorContract.GetDkg was just called")
	}
	callInfo := struct {
		Block *tonutils.BlockIDExt
	}{
		Block: block,
	}
	mock.lockGetDkg.Lock()
	mock.calls.GetDkg = append(mock.calls.GetDkg, callInfo)
	mock.lockGetDkg.Unlock()
	return mock.GetDkgFunc(block)
}

// GetDkgCalls gets all the calls that were made to GetDkg.
// Check the length with:
//
//	len(mockedCoordinatorContract.GetDkgCalls())
func (mock *CoordinatorContractMock) GetDkgCalls() []struct {
	Block *tonutils.BlockIDExt
} {
	var calls []struct {
		Block *tonutils.BlockIDExt
	}
	mock.lockGetDkg.RLock()
	calls = mock.calls.GetDkg
	mock.lockGetDkg.RUnlock()
	return calls
}

// GetPrevDKG calls GetPrevDKGFunc.
func (mock *CoordinatorContractMock) GetPrevDKG() (*DKG, error) {
	if mock.GetPrevDKGFunc == nil {
		panic("CoordinatorContractMock.GetPrevDKGFunc: method is nil but CoordinatorContract.GetPrevDKG was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetPrevDKG.Lock()
	mock.calls.GetPrevDKG = append(mock.calls.GetPrevDKG, callInfo)
	mock.lockGetPrevDKG.Unlock()
	return mock.GetPrevDKGFunc()
}

// GetPrevDKGCalls gets all the calls that were made to GetPrevDKG.
// Check the length with:
//
//	len(mockedCoordinatorContract.GetPrevDKGCalls())
func (mock *CoordinatorContractMock) GetPrevDKGCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetPrevDKG.RLock()
	calls = mock.calls.GetPrevDKG
	mock.lockGetPrevDKG.RUnlock()
	return calls
}

// GetUnsignedPegouts calls GetUnsignedPegoutsFunc.
func (mock *CoordinatorContractMock) GetUnsignedPegouts() ([]PegoutRecord, error) {
	if mock.GetUnsignedPegoutsFunc == nil {
		panic("CoordinatorContractMock.GetUnsignedPegoutsFunc: method is nil but CoordinatorContract.GetUnsignedPegouts was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetUnsignedPegouts.Lock()
	mock.calls.GetUnsignedPegouts = append(mock.calls.GetUnsignedPegouts, callInfo)
	mock.lockGetUnsignedPegouts.Unlock()
	return mock.GetUnsignedPegoutsFunc()
}

// GetUnsignedPegoutsCalls gets all the calls that were made to GetUnsignedPegouts.
// Check the length with:
//
//	len(mockedCoordinatorContract.GetUnsignedPegoutsCalls())
func (mock *CoordinatorContractMock) GetUnsignedPegoutsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetUnsignedPegouts.RLock()
	calls = mock.calls.GetUnsignedPegouts
	mock.lockGetUnsignedPegouts.RUnlock()
	return calls
}

// SendCommitments calls SendCommitmentsFunc.
func (mock *CoordinatorContractMock) SendCommitments(pegoutID uint64, validatorIdx uint16, commitments []byte) (*tlb.Transaction, error) {
	if mock.SendCommitmentsFunc == nil {
		panic("CoordinatorContractMock.SendCommitmentsFunc: method is nil but CoordinatorContract.SendCommitments was just called")
	}
	callInfo := struct {
		PegoutID     uint64
		ValidatorIdx uint16
		Commitments  []byte
	}{
		PegoutID:     pegoutID,
		ValidatorIdx: validatorIdx,
		Commitments:  commitments,
	}
	mock.lockSendCommitments.Lock()
	mock.calls.SendCommitments = append(mock.calls.SendCommitments, callInfo)
	mock.lockSendCommitments.Unlock()
	return mock.SendCommitmentsFunc(pegoutID, validatorIdx, commitments)
}

// SendCommitmentsCalls gets all the calls that were made to SendCommitments.
// Check the length with:
//
//	len(mockedCoordinatorContract.SendCommitmentsCalls())
func (mock *CoordinatorContractMock) SendCommitmentsCalls() []struct {
	PegoutID     uint64
	ValidatorIdx uint16
	Commitments  []byte
} {
	var calls []struct {
		PegoutID     uint64
		ValidatorIdx uint16
		Commitments  []byte
	}
	mock.lockSendCommitments.RLock()
	calls = mock.calls.SendCommitments
	mock.lockSendCommitments.RUnlock()
	return calls
}

// SendDKGClaim calls SendDKGClaimFunc.
func (mock *CoordinatorContractMock) SendDKGClaim(validatorIdx uint16, dkgUntil int64, culpritIdx uint16) (*tlb.Transaction, error) {
	if mock.SendDKGClaimFunc == nil {
		panic("CoordinatorContractMock.SendDKGClaimFunc: method is nil but CoordinatorContract.SendDKGClaim was just called")
	}
	callInfo := struct {
		ValidatorIdx uint16
		DkgUntil     int64
		CulpritIdx   uint16
	}{
		ValidatorIdx: validatorIdx,
		DkgUntil:     dkgUntil,
		CulpritIdx:   culpritIdx,
	}
	mock.lockSendDKGClaim.Lock()
	mock.calls.SendDKGClaim = append(mock.calls.SendDKGClaim, callInfo)
	mock.lockSendDKGClaim.Unlock()
	return mock.SendDKGClaimFunc(validatorIdx, dkgUntil, culpritIdx)
}

// SendDKGClaimCalls gets all the calls that were made to SendDKGClaim.
// Check the length with:
//
//	len(mockedCoordinatorContract.SendDKGClaimCalls())
func (mock *CoordinatorContractMock) SendDKGClaimCalls() []struct {
	ValidatorIdx uint16
	DkgUntil     int64
	CulpritIdx   uint16
} {
	var calls []struct {
		ValidatorIdx uint16
		DkgUntil     int64
		CulpritIdx   uint16
	}
	mock.lockSendDKGClaim.RLock()
	calls = mock.calls.SendDKGClaim
	mock.lockSendDKGClaim.RUnlock()
	return calls
}

// SendPubkeyPackage calls SendPubkeyPackageFunc.
func (mock *CoordinatorContractMock) SendPubkeyPackage(validatorIdx uint16, dkgUntil int64, sessionPublicKey []byte, pubkeyPackage []byte) (*tlb.Transaction, error) {
	if mock.SendPubkeyPackageFunc == nil {
		panic("CoordinatorContractMock.SendPubkeyPackageFunc: method is nil but CoordinatorContract.SendPubkeyPackage was just called")
	}
	callInfo := struct {
		ValidatorIdx     uint16
		DkgUntil         int64
		SessionPublicKey []byte
		PubkeyPackage    []byte
	}{
		ValidatorIdx:     validatorIdx,
		DkgUntil:         dkgUntil,
		SessionPublicKey: sessionPublicKey,
		PubkeyPackage:    pubkeyPackage,
	}
	mock.lockSendPubkeyPackage.Lock()
	mock.calls.SendPubkeyPackage = append(mock.calls.SendPubkeyPackage, callInfo)
	mock.lockSendPubkeyPackage.Unlock()
	return mock.SendPubkeyPackageFunc(validatorIdx, dkgUntil, sessionPublicKey, pubkeyPackage)
}

// SendPubkeyPackageCalls gets all the calls that were made to SendPubkeyPackage.
// Check the length with:
//
//	len(mockedCoordinatorContract.SendPubkeyPackageCalls())
func (mock *CoordinatorContractMock) SendPubkeyPackageCalls() []struct {
	ValidatorIdx     uint16
	DkgUntil         int64
	SessionPublicKey []byte
	PubkeyPackage    []byte
} {
	var calls []struct {
		ValidatorIdx     uint16
		DkgUntil         int64
		SessionPublicKey []byte
		PubkeyPackage    []byte
	}
	mock.lockSendPubkeyPackage.RLock()
	calls = mock.calls.SendPubkeyPackage
	mock.lockSendPubkeyPackage.RUnlock()
	return calls
}

// SendResetPegoutSigning calls SendResetPegoutSigningFunc.
func (mock *CoordinatorContractMock) SendResetPegoutSigning(pegoutID uint64, validatorIdx uint16) (*tlb.Transaction, error) {
	if mock.SendResetPegoutSigningFunc == nil {
		panic("CoordinatorContractMock.SendResetPegoutSigningFunc: method is nil but CoordinatorContract.SendResetPegoutSigning was just called")
	}
	callInfo := struct {
		PegoutID     uint64
		ValidatorIdx uint16
	}{
		PegoutID:     pegoutID,
		ValidatorIdx: validatorIdx,
	}
	mock.lockSendResetPegoutSigning.Lock()
	mock.calls.SendResetPegoutSigning = append(mock.calls.SendResetPegoutSigning, callInfo)
	mock.lockSendResetPegoutSigning.Unlock()
	return mock.SendResetPegoutSigningFunc(pegoutID, validatorIdx)
}

// SendResetPegoutSigningCalls gets all the calls that were made to SendResetPegoutSigning.
// Check the length with:
//
//	len(mockedCoordinatorContract.SendResetPegoutSigningCalls())
func (mock *CoordinatorContractMock) SendResetPegoutSigningCalls() []struct {
	PegoutID     uint64
	ValidatorIdx uint16
} {
	var calls []struct {
		PegoutID     uint64
		ValidatorIdx uint16
	}
	mock.lockSendResetPegoutSigning.RLock()
	calls = mock.calls.SendResetPegoutSigning
	mock.lockSendResetPegoutSigning.RUnlock()
	return calls
}

// SendRound1 calls SendRound1Func.
func (mock *CoordinatorContractMock) SendRound1(validatorIdx uint16, dkgUntil int64, round1Package []byte, r2PublicX25519 *[32]byte) (*tlb.Transaction, error) {
	if mock.SendRound1Func == nil {
		panic("CoordinatorContractMock.SendRound1Func: method is nil but CoordinatorContract.SendRound1 was just called")
	}
	callInfo := struct {
		ValidatorIdx   uint16
		DkgUntil       int64
		Round1Package  []byte
		R2PublicX25519 *[32]byte
	}{
		ValidatorIdx:   validatorIdx,
		DkgUntil:       dkgUntil,
		Round1Package:  round1Package,
		R2PublicX25519: r2PublicX25519,
	}
	mock.lockSendRound1.Lock()
	mock.calls.SendRound1 = append(mock.calls.SendRound1, callInfo)
	mock.lockSendRound1.Unlock()
	return mock.SendRound1Func(validatorIdx, dkgUntil, round1Package, r2PublicX25519)
}

// SendRound1Calls gets all the calls that were made to SendRound1.
// Check the length with:
//
//	len(mockedCoordinatorContract.SendRound1Calls())
func (mock *CoordinatorContractMock) SendRound1Calls() []struct {
	ValidatorIdx   uint16
	DkgUntil       int64
	Round1Package  []byte
	R2PublicX25519 *[32]byte
} {
	var calls []struct {
		ValidatorIdx   uint16
		DkgUntil       int64
		Round1Package  []byte
		R2PublicX25519 *[32]byte
	}
	mock.lockSendRound1.RLock()
	calls = mock.calls.SendRound1
	mock.lockSendRound1.RUnlock()
	return calls
}

// SendRound2 calls SendRound2Func.
func (mock *CoordinatorContractMock) SendRound2(validatorIdx uint16, dkgUntil int64, round2Packages []byte) (*tlb.Transaction, error) {
	if mock.SendRound2Func == nil {
		panic("CoordinatorContractMock.SendRound2Func: method is nil but CoordinatorContract.SendRound2 was just called")
	}
	callInfo := struct {
		ValidatorIdx   uint16
		DkgUntil       int64
		Round2Packages []byte
	}{
		ValidatorIdx:   validatorIdx,
		DkgUntil:       dkgUntil,
		Round2Packages: round2Packages,
	}
	mock.lockSendRound2.Lock()
	mock.calls.SendRound2 = append(mock.calls.SendRound2, callInfo)
	mock.lockSendRound2.Unlock()
	return mock.SendRound2Func(validatorIdx, dkgUntil, round2Packages)
}

// SendRound2Calls gets all the calls that were made to SendRound2.
// Check the length with:
//
//	len(mockedCoordinatorContract.SendRound2Calls())
func (mock *CoordinatorContractMock) SendRound2Calls() []struct {
	ValidatorIdx   uint16
	DkgUntil       int64
	Round2Packages []byte
} {
	var calls []struct {
		ValidatorIdx   uint16
		DkgUntil       int64
		Round2Packages []byte
	}
	mock.lockSendRound2.RLock()
	calls = mock.calls.SendRound2
	mock.lockSendRound2.RUnlock()
	return calls
}

// SendSignatures calls SendSignaturesFunc.
func (mock *CoordinatorContractMock) SendSignatures(pegoutID uint64, validatorIdx uint16, signatures [][]byte) (*tlb.Transaction, error) {
	if mock.SendSignaturesFunc == nil {
		panic("CoordinatorContractMock.SendSignaturesFunc: method is nil but CoordinatorContract.SendSignatures was just called")
	}
	callInfo := struct {
		PegoutID     uint64
		ValidatorIdx uint16
		Signatures   [][]byte
	}{
		PegoutID:     pegoutID,
		ValidatorIdx: validatorIdx,
		Signatures:   signatures,
	}
	mock.lockSendSignatures.Lock()
	mock.calls.SendSignatures = append(mock.calls.SendSignatures, callInfo)
	mock.lockSendSignatures.Unlock()
	return mock.SendSignaturesFunc(pegoutID, validatorIdx, signatures)
}

// SendSignaturesCalls gets all the calls that were made to SendSignatures.
// Check the length with:
//
//	len(mockedCoordinatorContract.SendSignaturesCalls())
func (mock *CoordinatorContractMock) SendSignaturesCalls() []struct {
	PegoutID     uint64
	ValidatorIdx uint16
	Signatures   [][]byte
} {
	var calls []struct {
		PegoutID     uint64
		ValidatorIdx uint16
		Signatures   [][]byte
	}
	mock.lockSendSignatures.RLock()
	calls = mock.calls.SendSignatures
	mock.lockSendSignatures.RUnlock()
	return calls
}

// SendSigningClaim calls SendSigningClaimFunc.
func (mock *CoordinatorContractMock) SendSigningClaim(pegoutID uint64, validatorIdx uint16, culpritIdx uint16) (*tlb.Transaction, error) {
	if mock.SendSigningClaimFunc == nil {
		panic("CoordinatorContractMock.SendSigningClaimFunc: method is nil but CoordinatorContract.SendSigningClaim was just called")
	}
	callInfo := struct {
		PegoutID     uint64
		ValidatorIdx uint16
		CulpritIdx   uint16
	}{
		PegoutID:     pegoutID,
		ValidatorIdx: validatorIdx,
		CulpritIdx:   culpritIdx,
	}
	mock.lockSendSigningClaim.Lock()
	mock.calls.SendSigningClaim = append(mock.calls.SendSigningClaim, callInfo)
	mock.lockSendSigningClaim.Unlock()
	return mock.SendSigningClaimFunc(pegoutID, validatorIdx, culpritIdx)
}

// SendSigningClaimCalls gets all the calls that were made to SendSigningClaim.
// Check the length with:
//
//	len(mockedCoordinatorContract.SendSigningClaimCalls())
func (mock *CoordinatorContractMock) SendSigningClaimCalls() []struct {
	PegoutID     uint64
	ValidatorIdx uint16
	CulpritIdx   uint16
} {
	var calls []struct {
		PegoutID     uint64
		ValidatorIdx uint16
		CulpritIdx   uint16
	}
	mock.lockSendSigningClaim.RLock()
	calls = mock.calls.SendSigningClaim
	mock.lockSendSigningClaim.RUnlock()
	return calls
}

// SendSigningShare calls SendSigningShareFunc.
func (mock *CoordinatorContractMock) SendSigningShare(pegoutID uint64, validatorIdx uint16, signingShares [][]byte) (*tlb.Transaction, error) {
	if mock.SendSigningShareFunc == nil {
		panic("CoordinatorContractMock.SendSigningShareFunc: method is nil but CoordinatorContract.SendSigningShare was just called")
	}
	callInfo := struct {
		PegoutID      uint64
		ValidatorIdx  uint16
		SigningShares [][]byte
	}{
		PegoutID:      pegoutID,
		ValidatorIdx:  validatorIdx,
		SigningShares: signingShares,
	}
	mock.lockSendSigningShare.Lock()
	mock.calls.SendSigningShare = append(mock.calls.SendSigningShare, callInfo)
	mock.lockSendSigningShare.Unlock()
	return mock.SendSigningShareFunc(pegoutID, validatorIdx, signingShares)
}

// SendSigningShareCalls gets all the calls that were made to SendSigningShare.
// Check the length with:
//
//	len(mockedCoordinatorContract.SendSigningShareCalls())
func (mock *CoordinatorContractMock) SendSigningShareCalls() []struct {
	PegoutID      uint64
	ValidatorIdx  uint16
	SigningShares [][]byte
} {
	var calls []struct {
		PegoutID      uint64
		ValidatorIdx  uint16
		SigningShares [][]byte
	}
	mock.lockSendSigningShare.RLock()
	calls = mock.calls.SendSigningShare
	mock.lockSendSigningShare.RUnlock()
	return calls
}

// SendStartDKG calls SendStartDKGFunc.
func (mock *CoordinatorContractMock) SendStartDKG() (*tlb.Transaction, error) {
	if mock.SendStartDKGFunc == nil {
		panic("CoordinatorContractMock.SendStartDKGFunc: method is nil but CoordinatorContract.SendStartDKG was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSendStartDKG.Lock()
	mock.calls.SendStartDKG = append(mock.calls.SendStartDKG, callInfo)
	mock.lockSendStartDKG.Unlock()
	return mock.SendStartDKGFunc()
}

// SendStartDKGCalls gets all the calls that were made to SendStartDKG.
// Check the length with:
//
//	len(mockedCoordinatorContract.SendStartDKGCalls())
func (mock *CoordinatorContractMock) SendStartDKGCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSendStartDKG.RLock()
	calls = mock.calls.SendStartDKG
	mock.lockSendStartDKG.RUnlock()
	return calls
}
