// Code generated by http://github.com/gojuno/minimock (v3.4.3). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/rsquad/ton-teleport-btc-periphery/lib/pkg/utils/console_executor.ConsoleExecutorInterface -o console_executor_interface_minimock.go -n ConsoleExecutorInterfaceMock -p mocks

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ConsoleExecutorInterfaceMock implements mm_console_executor.ConsoleExecutorInterface
type ConsoleExecutorInterfaceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcExecute          func(command string) (s1 string, err error)
	funcExecuteOrigin    string
	inspectFuncExecute   func(command string)
	afterExecuteCounter  uint64
	beforeExecuteCounter uint64
	ExecuteMock          mConsoleExecutorInterfaceMockExecute
}

// NewConsoleExecutorInterfaceMock returns a mock for mm_console_executor.ConsoleExecutorInterface
func NewConsoleExecutorInterfaceMock(t minimock.Tester) *ConsoleExecutorInterfaceMock {
	m := &ConsoleExecutorInterfaceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ExecuteMock = mConsoleExecutorInterfaceMockExecute{mock: m}
	m.ExecuteMock.callArgs = []*ConsoleExecutorInterfaceMockExecuteParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mConsoleExecutorInterfaceMockExecute struct {
	optional           bool
	mock               *ConsoleExecutorInterfaceMock
	defaultExpectation *ConsoleExecutorInterfaceMockExecuteExpectation
	expectations       []*ConsoleExecutorInterfaceMockExecuteExpectation

	callArgs []*ConsoleExecutorInterfaceMockExecuteParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ConsoleExecutorInterfaceMockExecuteExpectation specifies expectation struct of the ConsoleExecutorInterface.Execute
type ConsoleExecutorInterfaceMockExecuteExpectation struct {
	mock               *ConsoleExecutorInterfaceMock
	params             *ConsoleExecutorInterfaceMockExecuteParams
	paramPtrs          *ConsoleExecutorInterfaceMockExecuteParamPtrs
	expectationOrigins ConsoleExecutorInterfaceMockExecuteExpectationOrigins
	results            *ConsoleExecutorInterfaceMockExecuteResults
	returnOrigin       string
	Counter            uint64
}

// ConsoleExecutorInterfaceMockExecuteParams contains parameters of the ConsoleExecutorInterface.Execute
type ConsoleExecutorInterfaceMockExecuteParams struct {
	command string
}

// ConsoleExecutorInterfaceMockExecuteParamPtrs contains pointers to parameters of the ConsoleExecutorInterface.Execute
type ConsoleExecutorInterfaceMockExecuteParamPtrs struct {
	command *string
}

// ConsoleExecutorInterfaceMockExecuteResults contains results of the ConsoleExecutorInterface.Execute
type ConsoleExecutorInterfaceMockExecuteResults struct {
	s1  string
	err error
}

// ConsoleExecutorInterfaceMockExecuteOrigins contains origins of expectations of the ConsoleExecutorInterface.Execute
type ConsoleExecutorInterfaceMockExecuteExpectationOrigins struct {
	origin        string
	originCommand string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmExecute *mConsoleExecutorInterfaceMockExecute) Optional() *mConsoleExecutorInterfaceMockExecute {
	mmExecute.optional = true
	return mmExecute
}

// Expect sets up expected params for ConsoleExecutorInterface.Execute
func (mmExecute *mConsoleExecutorInterfaceMockExecute) Expect(command string) *mConsoleExecutorInterfaceMockExecute {
	if mmExecute.mock.funcExecute != nil {
		mmExecute.mock.t.Fatalf("ConsoleExecutorInterfaceMock.Execute mock is already set by Set")
	}

	if mmExecute.defaultExpectation == nil {
		mmExecute.defaultExpectation = &ConsoleExecutorInterfaceMockExecuteExpectation{}
	}

	if mmExecute.defaultExpectation.paramPtrs != nil {
		mmExecute.mock.t.Fatalf("ConsoleExecutorInterfaceMock.Execute mock is already set by ExpectParams functions")
	}

	mmExecute.defaultExpectation.params = &ConsoleExecutorInterfaceMockExecuteParams{command}
	mmExecute.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmExecute.expectations {
		if minimock.Equal(e.params, mmExecute.defaultExpectation.params) {
			mmExecute.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmExecute.defaultExpectation.params)
		}
	}

	return mmExecute
}

// ExpectCommandParam1 sets up expected param command for ConsoleExecutorInterface.Execute
func (mmExecute *mConsoleExecutorInterfaceMockExecute) ExpectCommandParam1(command string) *mConsoleExecutorInterfaceMockExecute {
	if mmExecute.mock.funcExecute != nil {
		mmExecute.mock.t.Fatalf("ConsoleExecutorInterfaceMock.Execute mock is already set by Set")
	}

	if mmExecute.defaultExpectation == nil {
		mmExecute.defaultExpectation = &ConsoleExecutorInterfaceMockExecuteExpectation{}
	}

	if mmExecute.defaultExpectation.params != nil {
		mmExecute.mock.t.Fatalf("ConsoleExecutorInterfaceMock.Execute mock is already set by Expect")
	}

	if mmExecute.defaultExpectation.paramPtrs == nil {
		mmExecute.defaultExpectation.paramPtrs = &ConsoleExecutorInterfaceMockExecuteParamPtrs{}
	}
	mmExecute.defaultExpectation.paramPtrs.command = &command
	mmExecute.defaultExpectation.expectationOrigins.originCommand = minimock.CallerInfo(1)

	return mmExecute
}

// Inspect accepts an inspector function that has same arguments as the ConsoleExecutorInterface.Execute
func (mmExecute *mConsoleExecutorInterfaceMockExecute) Inspect(f func(command string)) *mConsoleExecutorInterfaceMockExecute {
	if mmExecute.mock.inspectFuncExecute != nil {
		mmExecute.mock.t.Fatalf("Inspect function is already set for ConsoleExecutorInterfaceMock.Execute")
	}

	mmExecute.mock.inspectFuncExecute = f

	return mmExecute
}

// Return sets up results that will be returned by ConsoleExecutorInterface.Execute
func (mmExecute *mConsoleExecutorInterfaceMockExecute) Return(s1 string, err error) *ConsoleExecutorInterfaceMock {
	if mmExecute.mock.funcExecute != nil {
		mmExecute.mock.t.Fatalf("ConsoleExecutorInterfaceMock.Execute mock is already set by Set")
	}

	if mmExecute.defaultExpectation == nil {
		mmExecute.defaultExpectation = &ConsoleExecutorInterfaceMockExecuteExpectation{mock: mmExecute.mock}
	}
	mmExecute.defaultExpectation.results = &ConsoleExecutorInterfaceMockExecuteResults{s1, err}
	mmExecute.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmExecute.mock
}

// Set uses given function f to mock the ConsoleExecutorInterface.Execute method
func (mmExecute *mConsoleExecutorInterfaceMockExecute) Set(f func(command string) (s1 string, err error)) *ConsoleExecutorInterfaceMock {
	if mmExecute.defaultExpectation != nil {
		mmExecute.mock.t.Fatalf("Default expectation is already set for the ConsoleExecutorInterface.Execute method")
	}

	if len(mmExecute.expectations) > 0 {
		mmExecute.mock.t.Fatalf("Some expectations are already set for the ConsoleExecutorInterface.Execute method")
	}

	mmExecute.mock.funcExecute = f
	mmExecute.mock.funcExecuteOrigin = minimock.CallerInfo(1)
	return mmExecute.mock
}

// When sets expectation for the ConsoleExecutorInterface.Execute which will trigger the result defined by the following
// Then helper
func (mmExecute *mConsoleExecutorInterfaceMockExecute) When(command string) *ConsoleExecutorInterfaceMockExecuteExpectation {
	if mmExecute.mock.funcExecute != nil {
		mmExecute.mock.t.Fatalf("ConsoleExecutorInterfaceMock.Execute mock is already set by Set")
	}

	expectation := &ConsoleExecutorInterfaceMockExecuteExpectation{
		mock:               mmExecute.mock,
		params:             &ConsoleExecutorInterfaceMockExecuteParams{command},
		expectationOrigins: ConsoleExecutorInterfaceMockExecuteExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmExecute.expectations = append(mmExecute.expectations, expectation)
	return expectation
}

// Then sets up ConsoleExecutorInterface.Execute return parameters for the expectation previously defined by the When method
func (e *ConsoleExecutorInterfaceMockExecuteExpectation) Then(s1 string, err error) *ConsoleExecutorInterfaceMock {
	e.results = &ConsoleExecutorInterfaceMockExecuteResults{s1, err}
	return e.mock
}

// Times sets number of times ConsoleExecutorInterface.Execute should be invoked
func (mmExecute *mConsoleExecutorInterfaceMockExecute) Times(n uint64) *mConsoleExecutorInterfaceMockExecute {
	if n == 0 {
		mmExecute.mock.t.Fatalf("Times of ConsoleExecutorInterfaceMock.Execute mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmExecute.expectedInvocations, n)
	mmExecute.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmExecute
}

func (mmExecute *mConsoleExecutorInterfaceMockExecute) invocationsDone() bool {
	if len(mmExecute.expectations) == 0 && mmExecute.defaultExpectation == nil && mmExecute.mock.funcExecute == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmExecute.mock.afterExecuteCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmExecute.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Execute implements mm_console_executor.ConsoleExecutorInterface
func (mmExecute *ConsoleExecutorInterfaceMock) Execute(command string) (s1 string, err error) {
	mm_atomic.AddUint64(&mmExecute.beforeExecuteCounter, 1)
	defer mm_atomic.AddUint64(&mmExecute.afterExecuteCounter, 1)

	mmExecute.t.Helper()

	if mmExecute.inspectFuncExecute != nil {
		mmExecute.inspectFuncExecute(command)
	}

	mm_params := ConsoleExecutorInterfaceMockExecuteParams{command}

	// Record call args
	mmExecute.ExecuteMock.mutex.Lock()
	mmExecute.ExecuteMock.callArgs = append(mmExecute.ExecuteMock.callArgs, &mm_params)
	mmExecute.ExecuteMock.mutex.Unlock()

	for _, e := range mmExecute.ExecuteMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmExecute.ExecuteMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmExecute.ExecuteMock.defaultExpectation.Counter, 1)
		mm_want := mmExecute.ExecuteMock.defaultExpectation.params
		mm_want_ptrs := mmExecute.ExecuteMock.defaultExpectation.paramPtrs

		mm_got := ConsoleExecutorInterfaceMockExecuteParams{command}

		if mm_want_ptrs != nil {
			if mm_want_ptrs.command != nil && !minimock.Equal(*mm_want_ptrs.command, mm_got.command) {
				mmExecute.t.Errorf("ConsoleExecutorInterfaceMock.Execute got unexpected parameter command, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmExecute.ExecuteMock.defaultExpectation.expectationOrigins.originCommand, *mm_want_ptrs.command, mm_got.command, minimock.Diff(*mm_want_ptrs.command, mm_got.command))
			}
		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmExecute.t.Errorf("ConsoleExecutorInterfaceMock.Execute got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmExecute.ExecuteMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmExecute.ExecuteMock.defaultExpectation.results
		if mm_results == nil {
			mmExecute.t.Fatal("No results are set for the ConsoleExecutorInterfaceMock.Execute")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmExecute.funcExecute != nil {
		return mmExecute.funcExecute(command)
	}
	mmExecute.t.Fatalf("Unexpected call to ConsoleExecutorInterfaceMock.Execute. %v", command)
	return
}

// ExecuteAfterCounter returns a count of finished ConsoleExecutorInterfaceMock.Execute invocations
func (mmExecute *ConsoleExecutorInterfaceMock) ExecuteAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmExecute.afterExecuteCounter)
}

// ExecuteBeforeCounter returns a count of ConsoleExecutorInterfaceMock.Execute invocations
func (mmExecute *ConsoleExecutorInterfaceMock) ExecuteBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmExecute.beforeExecuteCounter)
}

// Calls returns a list of arguments used in each call to ConsoleExecutorInterfaceMock.Execute.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmExecute *mConsoleExecutorInterfaceMockExecute) Calls() []*ConsoleExecutorInterfaceMockExecuteParams {
	mmExecute.mutex.RLock()

	argCopy := make([]*ConsoleExecutorInterfaceMockExecuteParams, len(mmExecute.callArgs))
	copy(argCopy, mmExecute.callArgs)

	mmExecute.mutex.RUnlock()

	return argCopy
}

// MinimockExecuteDone returns true if the count of the Execute invocations corresponds
// the number of defined expectations
func (m *ConsoleExecutorInterfaceMock) MinimockExecuteDone() bool {
	if m.ExecuteMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ExecuteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ExecuteMock.invocationsDone()
}

// MinimockExecuteInspect logs each unmet expectation
func (m *ConsoleExecutorInterfaceMock) MinimockExecuteInspect() {
	for _, e := range m.ExecuteMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ConsoleExecutorInterfaceMock.Execute at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterExecuteCounter := mm_atomic.LoadUint64(&m.afterExecuteCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ExecuteMock.defaultExpectation != nil && afterExecuteCounter < 1 {
		if m.ExecuteMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ConsoleExecutorInterfaceMock.Execute at\n%s", m.ExecuteMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ConsoleExecutorInterfaceMock.Execute at\n%s with params: %#v", m.ExecuteMock.defaultExpectation.expectationOrigins.origin, *m.ExecuteMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcExecute != nil && afterExecuteCounter < 1 {
		m.t.Errorf("Expected call to ConsoleExecutorInterfaceMock.Execute at\n%s", m.funcExecuteOrigin)
	}

	if !m.ExecuteMock.invocationsDone() && afterExecuteCounter > 0 {
		m.t.Errorf("Expected %d calls to ConsoleExecutorInterfaceMock.Execute at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ExecuteMock.expectedInvocations), m.ExecuteMock.expectedInvocationsOrigin, afterExecuteCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ConsoleExecutorInterfaceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockExecuteInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ConsoleExecutorInterfaceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ConsoleExecutorInterfaceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockExecuteDone()
}
