name: Build and Publish Oracle

on:
  push:
    branches:
      - develop
      - sandbox
    paths:
      - 'oracle/**'
      - 'frost/**'
      - 'lib/**'
      - '.github/workflows/build-oracle-develop.yml'

env:
  WORKSPACE: ${{ github.workspace }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/develop' && 'develop' || 'sandbox' }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DOCR_USERNAME }}
          password: ${{ secrets.DOCR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          STAGE=${{ github.ref == 'refs/heads/develop' && 'dev' || 'sandbox' }}
          docker build -t registry.digitalocean.com/rsquad-$STAGE/ton-teleport-btc-oracle:latest -f ${{ env.WORKSPACE }}/oracle/Dockerfile .
          docker push registry.digitalocean.com/rsquad-$STAGE/ton-teleport-btc-oracle:latest