name: Build and Deploy (multi-environment)

on:
  push:
    branches:
      - develop
      - actions

jobs:
  build-and-deploy-develop-indexer:
    if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/actions' }}
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      APP_NAME: indexer
      STAGE: develop
      APP_NAMESPACE: ton-teleport-dev
    secrets:
      KUBE_CONFIG: ${{ secrets.DEV_KUBE_CONFIG }}

  build-and-deploy-develop-relayer:
    if: ${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/actions' }}
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      APP_NAME: relayer
      STAGE: develop
      APP_NAMESPACE: ton-teleport-dev
    secrets:
      KUBE_CONFIG: ${{ secrets.DEV_KUBE_CONFIG }}