name: Build and Deploy

on:
  push:
    branches:
      - develop
      - sandbox
      - oracle_automation
    paths-ignore:
      - '**/*.md'

jobs:
  develop:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      APPS: '["indexer", "relayer", "oracle"]'
      STAGE: develop
      APP_NAMESPACE: ton-teleport-dev
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

  develop-2:
    if: github.ref == 'refs/heads/develop-2'
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      APPS: '["indexer", "relayer"]'
      STAGE: develop-2
      APP_NAMESPACE: ton-teleport-dev-2
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

  sandbox:
    if: github.ref == 'refs/heads/sandbox'
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      APPS: '["indexer", "relayer"]'
      STAGE: sandbox
      APP_NAMESPACE: ton-teleport-sand
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

  oracle_automation:
    if: github.ref == 'refs/heads/oracle_automation'
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      APPS: '["oracle"]'
      STAGE: develop
      APP_NAMESPACE: ton-teleport-dev
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

