name: Deploy Apps

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch
    tags:
      - 'v*'  # Trigger on tags starting with 'v' (e.g., v1.0.0)
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  deploy-dev:
    if: github.event_name == 'push' && !contains(github.ref, 'refs/tags/') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [indexer, relayer]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "APP=${{ matrix.app }}" >> $GITHUB_ENV
          echo "STAGE=dev" >> $GITHUB_ENV

      - name: Run deploy script
        run: |
          chmod +x ./helm//deploy.sh
          ./helm/deploy.sh

  deploy-prod:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [indexer, relayer]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          echo "APP=${{ matrix.app }}" >> $GITHUB_ENV
          echo "STAGE=prod" >> $GITHUB_ENV

      - name: Run deploy script
        run: |
          chmod +x ./helm/deploy.sh
          ./helm/deploy.sh
