name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-prod-indexer:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      APP_NAME: indexer
      STAGE: production
      APP_NAMESPACE: ton-teleport-prod
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

  build-and-deploy-prod-relayer:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      APP_NAME: relayer
      STAGE: production
      APP_NAMESPACE: ton-teleport-prod
    secrets:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}