name: Deploy Environments

on:
  push:
    branches:
      - develop
      - actions

jobs:
  build_and_deploy:
    runs-on: self-hosted
    name: test secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        env:
          ENVIRONMENT: 'actions'
          EXPECTED_HASH: '2b0dcdd40016096b852d9d5b79de2ad570249dc8e4d4ebe4fa4ab81e2aa9af35'
          SECRET: ${{ secrets.SECRET }}
        run: |
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          cat "$SECRET"
          COMPUTED_HASH=$(echo -n "$SECRET" | sha256sum | awk '{print $1}')
          if [ "$COMPUTED_HASH" = "$EXPECTED_HASH" ]; then
              echo "result=actions" >> $GITHUB_ENV
          else
              echo "result=false" >> $GITHUB_ENV
          fi
          cat $GITHUB_ENV

