name: Deploy Environments

on:
  push:
    branches:
      - develop
      - actions

jobs:
  actions:
    runs-on: self-hosted
    name: actions env
    environment: actions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          if [ "$SECRET" = "actions" ]; then
              echo "result=a c t i o n s" >> $GITHUB_ENV
          else
              echo "result=other" >> $GITHUB_ENV
          fi
          cat $GITHUB_ENV
  develop:
    runs-on: self-hosted
    name: develop env
    environment: develop
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          if [ "$SECRET" = "actions" ]; then
              echo "result=actions" >> $GITHUB_ENV
          else
              echo "result=other" >> $GITHUB_ENV
          fi
          cat $GITHUB_ENV